import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/ThemeProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// providers wrap around application & access to data
// NextThemesProvider - light/dark mode
// generally client side
// switch light to dark mode (user interaction)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
        <main className="flex min-h-screen flex-col items-center p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-between text-sm lg:flex">
        <h2 className='text-2xl text-bold'>Pokemon Finder App</h2>
      </div>
        {children}
        </main>
        </ThemeProvider>
        </body>
    </html>
  )
}
